version: 2.1

jobs:
  benchmark:
    macos:
      xcode: "16.3.0"
    resource_class: m4pro.medium
    steps:
      - checkout
      - run:
          name: uptime
          command: uptime
      - run:
          name: ip
          command: curl ifconfig.me
      - run:
          name: system_profiler
          command: system_profiler -detailLevel mini
      - run:
          name: exec
          command: sh benchmark.sh

workflows:
  version: 2
  benchmark_workflow:
    jobs:
      - benchmark