version: 2.1

jobs:
  benchmark:
    macos:
      xcode: "16.3.0"
    resource_class: m4pro.medium
    steps:
      - checkout
      - run:
          name: uptime
          command: uptime
      - run:
          name: ip
          command: curl ifconfig.me
      - run:
          name: brew
          command: brew install fio
      - run:
          name: finger
          command: finger $USER
      - run:
          name: bench build
          command: sh benchmark.sh
      - run:
          name: bench disk
          command: sh test-local.sh

workflows:
  version: 2
  benchmark_workflow:
    jobs:
      - benchmark