name: Benchmark

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  macos:
    name: "Run"
    strategy:
      fail-fast: false
      matrix:
        image: ["ghcr.io/cirruslabs/macos-sonoma-xcode:15.2", "ghcr.io/cirruslabs/macos-runner:sonoma"]
    runs-on: ["${{ matrix.image }}", "low-priority"]
    steps:
      - uses: actions/checkout@v4
      - name: Xcode Select Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: 15.2
      - name: macOS version
        run: sw_vers
      - name: disk write
        run: time dd if=/dev/zero bs=1024k of=tstfile count=1024
      - name: disk read
        run: dd if=tstfile bs=1024k of=/dev/null count=1024
      - name: Run benchmark
        run: sh benchmark.sh
