name: Benchmark

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  macos:
    name: "Run"
    strategy:
      fail-fast: false
      matrix:
        image: [ "ghcr.io/cirruslabs/macos-runner:sequoia-xl"]
    runs-on: ["${{ matrix.image }}"]
    steps:
      - uses: actions/checkout@v4
      - name: macOS version
        run: sw_vers
      - name: Xcode Select Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: 16.3
      - name: Brew Install
        run: brew install fio
      - name: Run benchmark cpu
        run: sh benchmark.sh
      - name: Run benchmark disk
        run: sh test-local.sh
