name: Benchmark

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  macos:
    name: "Run (${{ matrix.image }}, cache=${{ matrix.cache }})"
    strategy:
      fail-fast: false
      matrix:
        image: ["ghcr.io/cirruslabs/macos-runner:tahoe"]
        cache: [false, true]
    runs-on: ["${{ matrix.image }}"]
    steps:
      - uses: actions/checkout@v4
      - name: macOS version
        run: sw_vers
      - name: Brew Install
        run: brew install fio
      - name: Run benchmark cpu
        if: ${{ !matrix.cache }}
        run: sh benchmark.sh
      - name: Run benchmark cpu with cache
        if: ${{ matrix.cache }}
        run: sh benchmark-cache.sh
      - name: Run benchmark disk io
        run: sh test-local.sh
