name: Benchmark

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  macos:
    name: "Run"
    strategy:
      fail-fast: false
      matrix:
        image: ["runner:sonoma", "runner:sequoia", "macos-latest"]
    runs-on: ["ghcr.io/cirruslabs/macos-${{ matrix.image }}"]
    steps:
      - uses: actions/checkout@v4
      - name: macOS version
        run: sw_vers
      - name: Uptime
        run: uptime
      - name: Run benchmark
        run: sh benchmark.sh
