name: Benchmark

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  macos:
    name: "Run"
    strategy:
      fail-fast: false
      matrix:
        image: ["sonoma-xcode:15.2", "runner:sonoma", "sonoma-xcode:15.2-xl", "runner:sonoma-xl"]
    runs-on: ["ghcr.io/cirruslabs/macos-${{ matrix.image }}", "low-priority"]
    steps:
      - uses: actions/checkout@v4
      - name: Xcode Select Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: 15.2
      - name: macOS version
        run: sw_vers
      - name: Uptime
        run: uptime
      - name: Run benchmark
        run: sh benchmark.sh
